/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scenarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a scenario (latest version) */
        get: operations["get"];
        /** Update a scenario (creates a new immutable version) */
        put: operations["update"];
        post?: never;
        /** Archive a scenario (soft delete; history preserved) */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/sensors/{sensorId}/link-budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set or clear a sensor's RF/optical link budget */
        put: operations["setLinkBudget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/miss-distance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the conjunction miss-distance threshold */
        put: operations["setMissDistance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/attitude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set a craft's attitude profile (lvlh / fixed) */
        put: operations["setAttitude"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my scenarios */
        get: operations["list"];
        put?: never;
        /** Create a scenario (v1, TLEs frozen from the catalog) */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a body-fixed sensor to a craft */
        post: operations["addSensor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/screening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screen the scenario against the full live catalog (snapshot) */
        post: operations["screen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/monte-carlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run seeded Monte Carlo dispersion for a deputy */
        post: operations["monteCarlo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an impulsive or finite ΔV burn to a deputy */
        post: operations["addManeuver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/station-keep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert closed-loop station-keeping burns (template) */
        post: operations["stationKeep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/rendezvous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert a two-impulse rendezvous (differential-corrected by default) */
        post: operations["rendezvous"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/rendezvous/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search the rendezvous arrival-time × revolution ΔV map */
        post: operations["searchRendezvous"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/phasing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert a phasing-orbit transfer (template) */
        post: operations["phasing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/nmc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert an NMC circumnavigation burn (template) */
        post: operations["nmc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert a V-bar/R-bar hold-point transfer (template) */
        post: operations["hold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/hohmann": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert a Hohmann transfer to a target altitude (template) */
        post: operations["hohmann"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/glideslope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert a constant-rate glideslope approach (template) */
        post: operations["glideslope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/collision-avoidance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert a collision-avoidance maneuver (template) */
        post: operations["cam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/collision-avoidance/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview a collision-avoidance ΔV (does not insert it) */
        post: operations["camPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a sun-keep-out or approach-corridor constraint */
        post: operations["addConstraint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/import/measured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a measured ephemeris (WOD CSV on the server) as a scenario */
        post: operations["importMeasured"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a scenario's version history */
        get: operations["versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/versions/{v}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one immutable version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/versions/{v}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff a version against its predecessor */
        get: operations["versionDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/export/oem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export propagated ephemerides as a CCSDS OEM file */
        get: operations["exportOem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the audit trail (who changed what, newest first) */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health, build info + streaming-contract version */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/sensors/{sensorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a sensor */
        delete: operations["removeSensor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/maneuvers/{maneuverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a maneuver */
        delete: operations["removeManeuver"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/constraints/{constraintId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a constraint */
        delete: operations["removeConstraint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RoleRef: {
            /** Format: int32 */
            noradId?: number;
        };
        ScenarioRequest: {
            name: string;
            fidelity?: string;
            timeRange: components["schemas"]["TimeRangeRequest"];
            chief: components["schemas"]["RoleRef"];
            deputies?: components["schemas"]["RoleRef"][];
        };
        TimeRangeRequest: {
            start: string;
            end: string;
        };
        AttitudeProfile: {
            mode?: string;
            quaternion?: number[];
        };
        Constraint: {
            id?: string;
            kind?: string;
            /** Format: int32 */
            hostNoradId?: number;
            sensorId?: string;
            /** Format: int32 */
            targetNoradId?: number;
            /** Format: double */
            limitDeg?: number;
            /** Format: double */
            rangeM?: number;
        };
        DeltaV: {
            /** Format: double */
            r?: number;
            /** Format: double */
            i?: number;
            /** Format: double */
            c?: number;
        };
        Fov: {
            type?: string;
            /** Format: double */
            halfAngleDeg?: number;
            /** Format: double */
            hDeg?: number;
            /** Format: double */
            vDeg?: number;
        };
        InitialState: {
            kind?: string;
            tle?: components["schemas"]["Tle"];
            datasetId?: string;
        };
        LinkBudget: {
            kind?: string;
            /** Format: double */
            eirpDbw?: number;
            /** Format: double */
            gOverTdbK?: number;
            /** Format: double */
            frequencyGhz?: number;
            /** Format: double */
            bandwidthHz?: number;
            /** Format: double */
            thresholdDb?: number;
        };
        Maneuver: {
            id?: string;
            kind?: string;
            epoch?: string;
            frame?: string;
            deltaV?: components["schemas"]["DeltaV"];
            /** Format: double */
            thrustN?: number;
            /** Format: double */
            ispSec?: number;
        };
        Mount: {
            boresightBody?: number[];
            /** Format: double */
            clockDeg?: number;
        };
        Role: {
            role?: string;
            /** Format: int32 */
            noradId?: number;
            name?: string;
            initialState?: components["schemas"]["InitialState"];
            maneuvers?: components["schemas"]["Maneuver"][];
            sensors?: components["schemas"]["Sensor"][];
            attitude?: components["schemas"]["AttitudeProfile"];
            constraints?: components["schemas"]["Constraint"][];
        };
        ScenarioBody: {
            /** Format: int32 */
            schemaVersion?: number;
            fidelity?: string;
            timeRange?: components["schemas"]["TimeRange"];
            chief?: components["schemas"]["Role"];
            deputies?: components["schemas"]["Role"][];
            /** Format: double */
            missDistanceThresholdM?: number;
        };
        ScenarioResponse: {
            id?: string;
            name?: string;
            ownerId?: string;
            createdAt?: string;
            /** Format: int32 */
            latestVersionNo?: number;
            /** Format: int32 */
            versionCount?: number;
            body?: components["schemas"]["ScenarioBody"];
        };
        Sensor: {
            id?: string;
            kind?: string;
            name?: string;
            fov?: components["schemas"]["Fov"];
            /** Format: double */
            minRangeM?: number;
            /** Format: double */
            maxRangeM?: number;
            mount?: components["schemas"]["Mount"];
            linkBudget?: components["schemas"]["LinkBudget"];
        };
        TimeRange: {
            start?: string;
            end?: string;
        };
        Tle: {
            line1?: string;
            line2?: string;
            epoch?: string;
        };
        LinkBudgetRequest: {
            kind?: string;
            /** Format: double */
            eirpDbw?: number;
            /** Format: double */
            gOverTdbK?: number;
            /** Format: double */
            frequencyGhz?: number;
            /** Format: double */
            bandwidthHz?: number;
            /** Format: double */
            thresholdDb?: number;
        };
        MissDistanceRequest: {
            /** Format: double */
            missDistanceThresholdM?: number;
        };
        AttitudeRequest: {
            /** Format: int32 */
            noradId?: number;
            mode?: string;
            quaternion?: number[];
        };
        SensorRequest: {
            /** Format: int32 */
            noradId?: number;
            kind?: string;
            name?: string;
            fovType?: string;
            /** Format: double */
            halfAngleDeg?: number;
            /** Format: double */
            hDeg?: number;
            /** Format: double */
            vDeg?: number;
            /** Format: double */
            minRangeM?: number;
            /** Format: double */
            maxRangeM?: number;
            /** Format: double */
            boresightX?: number;
            /** Format: double */
            boresightY?: number;
            /** Format: double */
            boresightZ?: number;
            /** Format: double */
            clockDeg?: number;
        };
        ConjunctionResult: {
            /** Format: int32 */
            scenarioNoradId?: number;
            scenarioName?: string;
            /** Format: int32 */
            catalogNoradId?: number;
            catalogName?: string;
            tcaEpoch?: string;
            /** Format: double */
            missDistanceM?: number;
        };
        ScreeningResult: {
            /** Format: double */
            thresholdM?: number;
            ranAt?: string;
            /** Format: int32 */
            catalogSize?: number;
            /** Format: int32 */
            candidateCount?: number;
            conjunctions?: components["schemas"]["ConjunctionResult"][];
        };
        MonteCarloRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
            /** Format: int32 */
            sampleCount?: number;
            /** Format: int64 */
            seed?: number;
            /** Format: double */
            posSigmaM?: number;
            /** Format: double */
            velSigmaMs?: number;
            /** Format: double */
            dvMagFrac?: number;
            /** Format: double */
            dvPointingDeg?: number;
        };
        EllipsoidSample: {
            /** Format: double */
            tSeconds?: number;
            center?: number[];
            semiAxes1Sigma?: number[];
            semiAxes3Sigma?: number[];
            quaternion?: number[];
        };
        MonteCarloResult: {
            /** Format: int32 */
            deputyNoradId?: number;
            name?: string;
            /** Format: int64 */
            seed?: number;
            /** Format: int32 */
            sampleCount?: number;
            /** Format: int32 */
            returnedTracks?: number;
            ranAt?: string;
            /** Format: int64 */
            epochMs?: number;
            /** Format: int32 */
            stepSeconds?: number;
            /** Format: int32 */
            cloudStride?: number;
            tracks?: number[][];
            ellipsoids?: components["schemas"]["EllipsoidSample"][];
            /** Format: int32 */
            corridorBreaches?: number;
        };
        ManeuverRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
            epoch: string;
            frame?: string;
            /** Format: double */
            r?: number;
            /** Format: double */
            i?: number;
            /** Format: double */
            c?: number;
            /** Format: double */
            thrustN?: number;
            /** Format: double */
            ispSec?: number;
        };
        StationKeepRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
            axis: string;
            /** Format: double */
            distanceM?: number;
            /** Format: double */
            intervalSec?: number;
            /** Format: int32 */
            corrections?: number;
        };
        RendezvousRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
            arrivalEpoch: string;
            corrected?: boolean;
            /** Format: int32 */
            nRev?: number;
        };
        RendezvousSearchRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
        };
        DvCell: {
            arrivalEpoch?: string;
            /** Format: int32 */
            nRev?: number;
            /** Format: double */
            dv1Ms?: number;
            /** Format: double */
            dv2Ms?: number;
            /** Format: double */
            totalDvMs?: number;
        };
        RendezvousSearchResult: {
            /** Format: int32 */
            deputyNoradId?: number;
            windowStart?: string;
            windowEnd?: string;
            /** Format: int32 */
            arrivalCount?: number;
            /** Format: int32 */
            revCount?: number;
            cells?: components["schemas"]["DvCell"][];
            cheapest?: components["schemas"]["DvCell"];
        };
        PhasingRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
            /** Format: int32 */
            phasingRevs?: number;
        };
        NmcRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
        };
        HoldRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
            axis: string;
            /** Format: double */
            distanceM?: number;
            arrivalEpoch: string;
        };
        HohmannRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
            /** Format: double */
            targetAltitudeKm?: number;
        };
        GlideslopeRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
            axis: string;
            /** Format: double */
            startRangeM?: number;
            /** Format: double */
            endRangeM?: number;
            /** Format: double */
            closingRateMps?: number;
            /** Format: int32 */
            segments?: number;
        };
        CamRequest: {
            /** Format: int32 */
            deputyNoradId?: number;
            /** Format: int32 */
            threatNoradId?: number;
            tcaEpoch: string;
            axis?: string;
            /** Format: double */
            targetMissM?: number;
            burnEpoch?: string;
        };
        CamPlanResult: {
            /** Format: int32 */
            deputyNoradId?: number;
            /** Format: int32 */
            threatNoradId?: number;
            axis?: string;
            burnEpoch?: string;
            tcaEpoch?: string;
            achievedTcaEpoch?: string;
            /** Format: double */
            dvR?: number;
            /** Format: double */
            dvI?: number;
            /** Format: double */
            dvC?: number;
            /** Format: double */
            dvMagnitudeMps?: number;
            /** Format: double */
            baselineMissM?: number;
            /** Format: double */
            achievedMissM?: number;
            converged?: boolean;
            note?: string;
        };
        ConstraintRequest: {
            /** Format: int32 */
            hostNoradId?: number;
            kind: string;
            sensorId?: string;
            /** Format: int32 */
            targetNoradId?: number;
            /** Format: double */
            limitDeg?: number;
            /** Format: double */
            rangeM?: number;
        };
        MeasuredImportRequest: {
            path: string;
            /** Format: int32 */
            noradId?: number;
        };
        ScenarioSummary: {
            id?: string;
            name?: string;
            createdAt?: string;
            /** Format: int32 */
            latestVersionNo?: number;
            /** Format: int32 */
            versionCount?: number;
            /** Format: int32 */
            chiefNoradId?: number;
            deputyNoradIds?: number[];
        };
        ScenarioVersionSummary: {
            /** Format: int32 */
            versionNo?: number;
            authorEmail?: string;
            createdAt?: string;
        };
        ScenarioVersionResponse: {
            scenarioId?: string;
            /** Format: int32 */
            versionNo?: number;
            authorId?: string;
            createdAt?: string;
            body?: components["schemas"]["ScenarioBody"];
        };
        Change: {
            op?: string;
            category?: string;
            detail?: string;
        };
        VersionDiff: {
            /** Format: int32 */
            versionNo?: number;
            /** Format: int32 */
            fromVersionNo?: number;
            changes?: components["schemas"]["Change"][];
        };
        AuditEntryResponse: {
            action?: string;
            actorEmail?: string;
            timestamp?: string;
            diffSummary?: string;
        };
        HealthResponse: {
            version?: string;
            buildTime?: string;
            dbStatus?: string;
            contractVersion?: string;
            serverTime?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setLinkBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sensorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkBudgetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    setMissDistance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissDistanceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    setAttitude: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttitudeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    addSensor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    screen: {
        parameters: {
            query?: {
                thresholdKm?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScreeningResult"];
                };
            };
        };
    };
    monteCarlo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MonteCarloResult"];
                };
            };
        };
    };
    addManeuver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManeuverRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    stationKeep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StationKeepRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    rendezvous: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RendezvousRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    searchRendezvous: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RendezvousSearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RendezvousSearchResult"];
                };
            };
        };
    };
    phasing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhasingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    nmc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NmcRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    hold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    hohmann: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HohmannRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    glideslope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlideslopeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    cam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CamRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    camPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CamRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CamPlanResult"];
                };
            };
        };
    };
    addConstraint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstraintRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    importMeasured: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasuredImportRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioVersionSummary"][];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                v: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioVersionResponse"];
                };
            };
        };
    };
    versionDiff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                v: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VersionDiff"];
                };
            };
        };
    };
    exportOem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    audit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditEntryResponse"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    removeSensor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sensorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    removeManeuver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                maneuverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    removeConstraint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                constraintId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
}
