/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scenarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/versions/{v}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RoleRef: {
            /** Format: int32 */
            noradId?: number;
        };
        ScenarioRequest: {
            name: string;
            fidelity?: string;
            timeRange: components["schemas"]["TimeRangeRequest"];
            chief: components["schemas"]["RoleRef"];
            deputies?: components["schemas"]["RoleRef"][];
        };
        TimeRangeRequest: {
            start: string;
            end: string;
        };
        InitialState: {
            kind?: string;
            tle?: components["schemas"]["Tle"];
        };
        Role: {
            role?: string;
            /** Format: int32 */
            noradId?: number;
            name?: string;
            initialState?: components["schemas"]["InitialState"];
        };
        ScenarioBody: {
            /** Format: int32 */
            schemaVersion?: number;
            fidelity?: string;
            timeRange?: components["schemas"]["TimeRange"];
            chief?: components["schemas"]["Role"];
            deputies?: components["schemas"]["Role"][];
        };
        ScenarioResponse: {
            id?: string;
            name?: string;
            ownerId?: string;
            createdAt?: string;
            /** Format: int32 */
            latestVersionNo?: number;
            /** Format: int32 */
            versionCount?: number;
            body?: components["schemas"]["ScenarioBody"];
        };
        TimeRange: {
            start?: string;
            end?: string;
        };
        Tle: {
            line1?: string;
            line2?: string;
            epoch?: string;
        };
        ScenarioSummary: {
            id?: string;
            name?: string;
            createdAt?: string;
            /** Format: int32 */
            latestVersionNo?: number;
            /** Format: int32 */
            versionCount?: number;
            /** Format: int32 */
            chiefNoradId?: number;
            deputyNoradIds?: number[];
        };
        ScenarioVersionResponse: {
            scenarioId?: string;
            /** Format: int32 */
            versionNo?: number;
            authorId?: string;
            createdAt?: string;
            body?: components["schemas"]["ScenarioBody"];
        };
        HealthResponse: {
            version?: string;
            buildTime?: string;
            dbStatus?: string;
            contractVersion?: string;
            serverTime?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                v: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioVersionResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
