{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbit.secretName" . }}
  labels:
    {{- include "orbit.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  keycloak-admin-password: {{ .Values.secrets.keycloakAdminPassword | quote }}
{{- end }}
